var faker = require('faker/locale/fr');

module.exports = {
    name: 'color',
    description: "Changer les couleurs et les noms",
    execute(message, args, bot) {
        let names = [
            "l'Équipage de Tromperie",
            "les Bandits d'Extinction",
            "le Gang Oublié",
            "la Tuerie du Bouclier",
            "le Sacrement de la Nuit",
            "la Prophétie d'Aigle",
            "la Bande Oubliée",
            "les Compagnon Classifiés",
            "les Voix des Sacrés",
            "les Sentinelles Perdues",
            "les Anges des Rejetés",
            "la Ruine des Cobras",
            "les Vestiges des Abominables",
            "les Héros des Pieux",
            "les Bannis des Immoraux",
            "les Brutes des Agneaux",
            "le Sacrement des Croyants",
            "le Génocide de Démolition",
            "la Dynastie des Buffles",
            "la Clémence des Corruptions",
            "le Silence des Pourris",
            "la Liaison des Putrides",
            "la Prédation des Moutons",
            "les Esprits de Jungle",
            "la Peste des Éhontés",
            "la Prime de Défi",
            "les Voix d'Obscurité",
            "les Anges du Vampire",
            "les Harceleurs des Carieux",
            "les Ennemis de la Jungle",
            "les Murmures d'Inconnu",
            "la Sérénité Détestable",
            "les Réfugiés du Tigre",
            "les Sourires de Colère",
            "les Séducteurs Cramoisis",
            "le Jugement en Miettes",
            "la Vigueur Sincère",
            "l'Harmonie des Ours",
            "la Tombe des Trompé",
            "la Terreur des Malades",
            "l'Intention Perdue",
            "l'Aurore du Faucon",
            "l'Espoir de Démolition",
            "le Cauchemar Damné",
            "le Cauchemar du Tigre",
            "la Voix des Colombes",
            "la Purification Sereine",
            "le Fardeau Malade",
            "l'Intention de l'Océan",
            "les Gardes de Damnation",
            "les Esprits du Dernier Âge",
            "l'Équipe Promise",
            "la Protection de Courage",
            "les Visiteurs du Lac",
            "la Prophétie de Peur",
            "le Prestige Ambitieux",
            "la Mafia des Héros",
            "les Gardiens des Blaireaux",
            "la Terreur Sombre",
            "la Voix de la Galaxie",
            "le Patrimoine de Sacrilège",
            "la Force Pieuse",
            "les Brutes des Féroces",
            "la Renaissance Misérable",
            "la Tombe des Sacrés",
            "les Mystiques du Faucon",
            "le Syndicat des Morts-Vivants",
            "la Fin de la Nature",
            "la Poursuite Méchante",
            "les Enchanteurs des Griffes",
            "la Paix de l'Alpha",
            "la Résistance de Foi",
            "les Immortels des Cobras",
            "les Mystères Morts",
            "le Murmure du Loup",
            "les Ancients des Nobles",
            "les Boucliers de Peur",
            "les Bergers d'Émeraude",
            "les Revenants Dévoués",
            "l'Honneur des Corruptions",
            "le Destin des Obscènes",
            "l'Assaut des Pauvres",
            "les Satins Communs",
            "l'Enfer d'Extinction",
            "le Chagrin du Rat",
            "l'Agression du Lynx",
            "les Gladiateurs Promis",
            "les Vengeurs Éthérés",
            "la Prime Pure",
            "la Rumeur de Sacrilège",
            "les Templiers des Bisons",
            "le Prestige des Infernaux",
            "la Stratégie du Loup",
            "les Chevaliers de la Forêt",
            "les Reliques Obscènes",
            "les Croisés Scandaleux",
            "la Guerre Corrompue",
            "le Cri des Loyaux",
            "les Citoyens Écartés",
            "l'Agression du Renard",
            "le Devoir du Monde",
            "les Chevaliers de la Cavalerie",
            "le Fardeau des Téméraires",
            "les Glaives Spirituels",
            "la Légion Naturelle",
            "le Don Puissant",
            "la Sanction des Cobras",
            "les Démons de la Nuit",
            "la Misère des Optimistes",
            "la Damnation des Libellules",
            "les Bourreaux de la Lance",
            "les Présages du Jaguar",
            "la Peste du Crocodile",
            "les Disciples de Vaillance",
            "les Titans des Pourris",
            "les Frères des Humbles",
            "la Tempête Avide",
            "la Liaison du Défi",
            "le Cauchemar des Aigles",
            "la Légion Cachée",
            "les Croisés des Vertueux",
            "les Revenants des Méchants",
            "la Révélation Précise",
            "le Venin des Humbles",
            "les Voyants de la Nuit",
            "les Bouchers Électriques",
            "la Tyrannie Vaincue",
            "les Guerriers des Forts",
            "les Enfants des Malades",
            "les Sorciers d'Émeraude",
            "les Enchanteurs Ruinés",
            "l'Équipage du Chien",
            "les Mémoires du Destin",
            "l'Attaque de Disparation",
            "la Prime des Moutons",
            "la Tempête des Infernaux",
            "les Voyous Ruinés",
            "l'Illusion Avide",
            "l'Aube Obscure",
            "la Tempête de Perversion",
            "l'Assaut de Délaissement",
            "le Prestige des Buffles",
            "la Synergie d'Alchimie",
            "les Berserkers Infernaux",
            "la Poursuite de Fureur",
            "les Vautours des Blaireaux",
            "l'Horreur Éhontée",
            "la Grâce Cachée",
            "les Flammes Angéliques",
            "le Trésor Naturel",
            "l'Honneur d'Étoile",
            "le Coup des Optimistes",
            "la Poursuite de la Forêt",
            "la Brigade du Chacal",
            "les Sourires de la Corruption",
            "les Hérauts Vigoureux",
            "le Vol du Vampire",
            "l'Armée de Prime",
            "les Étrangers des Propres",
            "les Asticots des Sangliers",
            "les Voix Perpétuelles",
            "les Chercheurs Classifiés",
            "la Bande des Pauvres",
            "la Rédemption de Défi",
            "le Service des Putrides",
            "les Vétérans des Pumas",
            "les Anges Cramoisis",
            "les Protecteurs du Mouton",
            "les Archers Honorés",
            "le Paradoxe Précis",
            "les Gladiateurs des Trucs",
            "les Enchanteurs des Promesses",
            "la Frénésie Féroce",
            "le Génocide des Morts-Vivants",
            "les Criminels Oubliés",
            "la Puissance d'Aigle",
            "les Ogives du Talon",
            "les Commandos de Lumière",
            "la Vigueur des Faibles",
            "le Sacrement de Peur",
            "les Résidents de Trahison",
            "la Croyance Dévouée",
            "l'Horreur de Fureur",
            "le Chagrin du Contrat",
            "la Fête d'Inconnu",
            "les Chevaliers des Infernaux",
            "les Chacals de Colère",
            "la Traité Téméraire",
            "le Devoir Perpétuel",
            "les Stewards de Disparation",
            "l'Harmonie Bleue",
            "les Maîtres du Dernier Âge",
            "la Mafia des Oubliés",
            "la Tirade de la Griffe",
            "les Cendres d'Assassins",
            "la Foi du Serpent",
            "la Bande de Condamnation",
            "les Gangsters du Cerf",
            "les Chevaliers des Courbeaux",
            "les Flammes de Vaillance"
        ];

        message.guild.roles.forEach(role => {
            let newName = faker.random.arrayElement(names);
            role.edit({
                color: "RANDOM",
                name: newName.toString().toUpperCase()
            });
            names.splice(names.indexOf(newName), 1);
        })
    }
};

